----------------------------------------------------------------------   2018-06-20   Version 2.0 ---------------------------------------------------------------------- - CWD is now expected to be the parent of the raw and jpg directories. - This script now produces a shell script that can be executed. The output   can be redirected into a file. Grant execute permission to the file,   and execute, to remove the unwanted raw files. - Look for raw directory: raw, RAW, cr2, CR2 - Error checking for raw directory - Look for jpg directory: jpg, JPG - Error checking for jpg directory - Verify that there are files in the raw directory and execute if > 1.

diff --git a/cullphotos b/cullphotos
--- a/cullphotos
+++ b/cullphotos
@@ -4,15 +4,17 @@
 # Constants
 # ----------------------------------------
 readonly origIFS=$IFS
-readonly progVer="1.0"
+readonly progVer="2.0"
 readonly dashLineLength=60
+readonly progName=$(basename $0)
 readonly uninitialized="UNINITIALIZED"
 
 # ----------------------------------------
 # Globals
 # ----------------------------------------
-debug="TRUE"    #debug
-debug="FALSE"   #debug
+debug="TRUE"
+debug="FALSE"
+error="FALSE"
 recordCount=0
 firstLinePrinted="FALSE"
 
@@ -27,7 +29,7 @@ for i in $libList; do
     else
         printf "%s\n" "ERROR: Library file not found. Could not source library file."
         printf "%s\n" "File: $i"
-        exit
+        exit 1
     fi
 done
 
@@ -43,31 +45,88 @@ if [[ "$debug" == "TRUE" ]]; then
   printf "%s\n"  "++ dashLineLength ............... .$dashLineLength."
 fi
 
-if [[ ! -d ../jpg ]]; then
-  printf "%s\n"  "++ ERROR: ../jpg directory not found."
-  printf "%s\n"  "   This script expects a ../jpg directory where .JPG files"
-  printf "%s\n"  "   can be found. You may need to cd() to that directory."
-  printf "%s\n"  "   Now exiting ...."
-  exit 1                            # Error 
+# Make sure the "jpg" directory exists.
+if [[ ! -d jpg && ! -d JPG ]]; then
+  printf "%s\n"  "++ ERROR: jpg directory not found. One of: jpg, JPG"
+  printf "%s\n"  "   This script expects a jpg directory where .JPG files are found."
+  error="TRUE"
+else
+    if [[ -d jpg ]];then
+        jpgDir=jpg
+    elif [[ -d JPG ]];then
+        jpgDir=JPG
+    fi
+    if [ "$debug" == "TRUE" ]; then
+     printf "%s\n" "jpg directory .............. $jpgDir"
+    fi
 fi
 
-for i in *; do
+# Make sure the "raw" directory exists.
+if [[ ! -d raw && ! -d cr2 && ! -d RAW && ! -d CR2 ]]; then
+  printf "%s\n"  "++ ERROR: raw directory name not found. One of: raw, RAW, cr2, CR2"
+  printf "%s\n"  "   This script expects raw directory where .CR2 files are found."
+  error="TRUE"
+else
+    if [[ -d raw ]];then
+        rawDir=raw
+    elif [[ -d RAW ]];then
+        rawDir=RAW
+    elif [[ -d cr2 ]];then
+        rawDir=cr2
+    elif [[ -d CR2 ]];then
+        rawDir=CR2
+    fi
+    if [ "$debug" == "TRUE" ]; then
+        printf "%s\n" "raw directory .............. $rawDir"
+    fi
+fi
+
+if [[ $error == "TRUE" ]]; then
+  printf "%s\n"  "++ Now exiting ...."
+  exit 2                            # Error 
+fi
+
+rawCount=$(ls $rawDir | wc -l)
+printf -v rawCount "%d" $rawCount
+    if [ "$debug" == "TRUE" ]; then
+        printf "%s\n" "RAW count .................. $rawCount"
+    fi
+
+if [[ $rawCount == 0 ]];then
+  printf "%s\n"  "Empty $rawDir directory. Exit."
+  printf "%s\n"  "   Since there are no raw files, no need to run."
+  printf "%s\n"  "Now exiting ...."
+fi
+
+for i in $rawDir/*; do
     ((recordCount++))
-    fileName=${i%%.*}               # Longest match from the end.
-    jpgFile="../jpg/${fileName}.JPG"
+    fileName=$(basename $i)
+    fileName=${fileName%%.*}               # Longest match from the end.
+    jpgFile="jpg/${fileName}.JPG"
+    rawFile="raw/${fileName}.CR2"
     deleteCandidate="$i"
 
     if [ "$debug" == "TRUE" ]; then
         DashLine dashLineLength "-" " $recordCount " 10
         printf "%s\n" "RAW file ......................... $fileName"
-        printf "%s\n" "Look for JPG ..................... $jpgFile"
+        printf "%s\n" "JPG file ......................... $jpgFile"
         printf "%s\n" "Delete candidate ................. $deleteCandidate"
     fi
 
     if [ ! -e $jpgFile ]; then
+        ((deleteCount++))
         if [[ "$debug" == "TRUE" ]]; then
+            printf "%s\n" "Delete count ..................... $deleteCount"
             printf "%s\n" "++ JPG not Found: DELETE RAW"
         fi
+        if [[ $deleteCount == 1 ]]; then
+            printf "%s\n" "#!/bin/bash"
+            printf "%s\n"
+            printf "%s\n" "# This file Created by: $progName, ver $progVer"
+            printf "%s\n" "# Grant execute permission to this file and execute."
+            printf "%s\n"
+        fi
+
         printf "%s\n" "rm $deleteCandidate"
     else
         if [[ "$debug" == "TRUE" ]]; then
@@ -77,6 +136,10 @@ for i in *; do
 
 
 done            # while read recordID  ...
+if [[ $deleteCount > 0 ]]; then
+    printf "%s\n"
+    printf "%s\n" "# Files to delete ..... $deleteCount"
+fi
 
 # ----------------------------------------
 # ----------------------------------------
@@ -110,6 +173,20 @@ give it execute permission, and the raw files are easily and reliably deleted.
 -------------
 -- History --
 -------------
+
+----------------------------------------------------------------------
+  2018-06-20
+  Version 2.0
+----------------------------------------------------------------------
+- CWD is now expected to be the parent of the raw and jpg directories.
+- This script now produces a shell script that can be executed. The output
+  can be redirected into a file. Grant execute permission to the file,
+  and execute, to remove the unwanted raw files.
+- Look for raw directory: raw, RAW, cr2, CR2
+- Error checking for raw directory
+- Look for jpg directory: jpg, JPG
+- Error checking for jpg directory
+- Verify that there are files in the raw directory and execute if > 1.
 
 ----------------------------------------------------------------------
   2018-06-17
